# Generated by Django 4.2.4 on 2023-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dish_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='meal_type',
            field=models.CharField(choices=[('starters', 'Starters'), ('main_dishes', 'Main Dishes'), ('fast_food', 'Fast Food'), ('desserts', 'Desserts')], max_length=200),
        ),
    ]
